on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_version_increment:
    if: contains(github.event.pull_request.labels.*.name, 'release') || contains(github.event.pull_request.labels.*.name, 'build')
    runs-on: ubuntu-latest

    steps:
      - uses: joutvhu/get-release@v1
        id: get_latest_tag
        with:
          latest: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Get the head version
        id: get_head_version
        run: |
          HEAD_OUTPUT=$(grep -E '^version:' pubspec.yml | sed -E 's/version: *//')
          echo "HEAD_OUTPUT=v$HEAD_OUTPUT" >> $GITHUB_OUTPUT

      - name: Check version increment
        run: |
          if [ ${{ steps.get_head_version.outputs.HEAD_OUTPUT }} == ${{ steps.get_latest_tag.outputs.tag_name }} ]; then
            echo "Version number has not changed in the PR."
            exit 1
          fi
